### ISSUE TITLE
How can we use this plugin?

### ISSUE THREAD

**Issue by ahmedfaical** [Dimon24021993/vue-menu-aim#1]
Hello, there is no documentation that explain how ca we use this plugin?

**Comment by Dimon24021993** [comment]
Update this info with last commit. Have You got all necessary information?

**Comment by ahmedfaical** [comment]
Thank you so much.
I m using vuetify too so it's perfect.
I will start using your menu for a big project. If have more questions and
issues can i send you email?

**Comment by ahmedfaical** [comment]
Yes, Thank you so much. I m using vuetify too so it's perfect.
i just have one last question if i use your markup :
`
<v-list class="menu-aim">
    <template v-for="(element) in catalog">
      <v-list-tile :key="element.title" :to="`/groups/${element.id}`" class="menu-li">
        <v-list-tile-content class="main-group-title">{{element.title}}</v-list-tile-content>
        <v-list-tile-action>
          <v-icon color="grey">navigate_next</v-icon>
        </v-list-tile-action>
      </v-list-tile>
    </template>
  </v-list>`
Where can i put the submenus ?

**Comment by ahmedfaical** [comment]
Yes, Thank you so much. But it still not yet clear.
i just have one last question i created a codesandbox example implementing this 

```
<div id="app" class="menu-aim">
    <ul>
      <li class="menu-li" v-for="(element) in catalog" :key="element.title">
        <span>{{element.title}}</span>
      </li>
    </ul>
    <div class="sub-menu">
      <ul>
        <li>Hello 1</li>
        <li>Hello 2</li>
        <li>Hello 3</li>
        <li>Hello 4</li>
      </ul>
    </div>
  </div>
```
In this example i want to show submenu with aim, can you help me ? 
https://codesandbox.io/s/vue-template-g51cz

**Comment by Dimon24021993** [comment]
I will add to options "width" & "height" fields, coz U dont set width of main menu, and angle of menu was too small to can see it

fixed wariant of your code
https://codesandbox.io/s/vue-template-tdjfn


P.S. "activate" func  (in options)  - it's mouseOver event handler, but need to add some info to bind scripts (like "data-***")

**Comment by ahmedfaical** [comment]
Thank you for your reply. Now it's exactly what i want.
